yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'  # Так хотят тесты

yatube/posts/models.py
from django.db import models

from users.models import User
from .constants import (NUMBER_OF_POST_CHARS_DISPLAYED,
                        NUMBER_OF_COMMENT_CHARS_DISPLAYED)


class Group(models.Model):
    """Представляет группу записей."""

    title = models.CharField('Название', max_length=200)
    slug = models.SlugField('Идентификатор', unique=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа записей'
        verbose_name_plural = 'Группы записей'

    def __str__(self):
        return self.title


class Published(models.Model):
    """Представляет нечто опубликованное (ABC)."""

    pub_date = models.DateTimeField('Опубликовано', auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ['-pub_date']


class Post(Published):
    """Представляет опубликованную запись."""

    IMAGES_UPLOAD_PATH = 'posts/'

    text = models.TextField(
        'Текст записи',
        help_text='Введите текст записи',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='posts',
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться запись',
        related_name='posts',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    image = models.ImageField(
        'Иллюстрация',
        help_text='Можно загрузить файл с иллюстрацией',
        upload_to=IMAGES_UPLOAD_PATH,
        blank=True,
    )

    class Meta(Published.Meta):
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.text[:NUMBER_OF_POST_CHARS_DISPLAYED]


class Comment(Published):
    """Представляет комментарий к записи."""

    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='comments',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name='Запись',
        related_name='comments',
        on_delete=models.CASCADE,
    )

    class Meta(Published.Meta):
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:NUMBER_OF_COMMENT_CHARS_DISPLAYED]


class Follow(models.Model):
    """Представляет подписку посетителя сайта на автора."""

    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        related_name='following',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_follows_author_only_once'
            ),
        ]

    def __str__(self):
        return f'{self.user.username} --> {self.author.username}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Представляет форму для создания/изменения записи."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Представляет форму для создания комментария."""

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.cache import cache_page

from users.models import User
from .models import Post, Group, Follow
from .forms import PostForm, CommentForm
from .utils import make_page_obj
from .constants import (NUMBER_OF_POSTS_ON_MAIN_PAGE,
                        NUMBER_OF_POSTS_ON_GROUP_PAGE,
                        NUMBER_OF_POSTS_ON_USER_PAGE,
                        )


@cache_page(20, key_prefix='index_page')
def index(request):
    """Отображает главную страницу."""
    posts = Post.objects.select_related('group')
    page_obj = make_page_obj(request, posts, NUMBER_OF_POSTS_ON_MAIN_PAGE)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Отображает страницу группы slug."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = make_page_obj(request, posts, NUMBER_OF_POSTS_ON_GROUP_PAGE)
    context = {
        'page_obj': page_obj,
        'group': group,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Отображает страницу пользователя username."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    page_obj = make_page_obj(request, posts, NUMBER_OF_POSTS_ON_USER_PAGE)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )

    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Отображает страницу записи post_id."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Отображает страницу создания новой записи."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            reverse('posts:profile', args=[request.user.username])
        )

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Отображает страницу редактирования записи post_id."""
    post = get_object_or_404(Post, id=post_id)
    if post.author.username != request.user.username:
        return redirect(
            reverse('posts:post_detail', args=[post_id])
        )

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if request.method == 'POST' and form.is_valid():
        post.save()
        return redirect(
            reverse('posts:post_detail', args=[post_id])
        )

    context = {'form': form, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Обрабатывает запрос на создание комментария к записи."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Отображает страницу с постами авторов, на которых подписан текущий
    пользователь.
    """
    posts = Post.objects.filter(
        author__following__user=request.user
    ).select_related(
        'group'
    )
    page_obj = make_page_obj(request, posts, NUMBER_OF_POSTS_ON_MAIN_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Обрабатывает запрос на создание подписки на автора username."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(author=author, user=user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Обрабатывает запрос на удаление подписки на автора username."""
    author = get_object_or_404(User, username=username)
    user = request.user
    Follow.objects.filter(author=author, user=user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новая запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/form_errors.html' %}
            <form method="post" action="{{ request.path }}"
             enctype="multipart/form-data"
            >
              {% csrf_token %}
              {% include 'includes/form_fields.html' %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние записи избранных авторов{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  <div class="container py-5">
    <h1>Последние записи избранных авторов</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' with group_ref=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}.{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html'  with group_ref=False %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with index=True %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html'  with group_ref=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex
          justify-content-between align-items-center"
        >
          Всего постов автора:  <span >{{ post.author.posts.all.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% include 'posts/includes/post_image.html' %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              {% include 'includes/form_fields.html' %}
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href={% url 'posts:profile' comment.author.username %}>
                {{ comment.author.username }}
              </a>
            </h5>
            <p>{{ comment.text|linebreaksbr }}</p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
      <h5>Подписчиков: {{ author.following.count }}</h5>
      <h5>Подписок: {{ author.follower.count }}</h5>
      {% if user.is_authenticated and user != author %}
        {% if following %}
          <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}"
            role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}"
            role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html'  with group_ref=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}